<a href="https://colab.research.google.com/github/saurabhgoyal12/sg-python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create Array

In [11]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
import numpy as np
mul_arr = np.array([[1,2,3],
                   [4,5,6]])
print(mul_arr)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
arr = np.array([5,3,6,2,9,7,4])
print(arr)
arr.sort()
print(arr)

[5 3 6 2 9 7 4]
[2 3 4 5 6 7 9]


In [7]:
import numpy as np
arr = np.array([5,3,6,2,9,7,4])
print(arr)
arr.argsort()
print(arr)

[5 3 6 2 9 7 4]
[5 3 6 2 9 7 4]


In [9]:
import numpy as np
s = np.arange(0,10)
print(s)
print(s[:6:3])


[0 1 2 3 4 5 6 7 8 9]
[0 3]
